### ISSUE TITLE
[official] missing options for Docker

### ISSUE THREAD

**Issue by arukuka** [SamurAI-Coding/Software2017-18#21]
Dockerでプレイヤーを停止/再開するコマンドが実装されていません。

**Comment by takashi-chikayama** [comment]
> Dockerでプレイヤーを停止/再開するコマンドが実装されていません。
>
昨年度のものと同様の実装をするのが良さそうでしょうか。留意点として、参加者が手元でインストールして実行する際に 
docker が必要とするのは参加障壁を高くしそうなので、VM 
を使わずに直接動かすこともできるようにしておくのがよいだろうと思います。昨年は公開したものには 
docker 
を使う機能がなく、予選/決勝で用いたものにだけ追加したような記憶もありますが、できれば 
docker 
での実行用のオプションがなければ直接呼び出すようにするのが良いのではないかと思います。

近山

**Comment by arukuka** [comment]
コメントありがとうございます。

そのように実装しようと思います。
