### ISSUE TITLE
course.length(goal line) identify with obstacle.length

### ISSUE THREAD

**Issue by arukuka** [SamurAI-Coding/Software2017-18#25]
ゴールラインとしてコース長 <img src="https://latex.codecogs.com/gif.latex?\inline&space;l" /> が与えられていますが、
格子点、障害点のy座標については限りがありません。

しかしながら現在のeditor, official, player, viewerの実装では、障害点のy座標が
コース長 <img src="https://latex.codecogs.com/gif.latex?\inline&space;l" /> 未満に限られています。

https://github.com/SamurAI-Coding/Software2017-18/blob/b0065fbea27b5d2fe096bcd0d315e87b7052ea29/documents/rule-en.tex#L38-L46

https://github.com/SamurAI-Coding/Software2017-18/blob/b0065fbea27b5d2fe096bcd0d315e87b7052ea29/documents/rule-jp.tex#L38-L46

**Comment by arukuka** [comment]
TODO
- [x] editor (@takashi-chikayama) fe85391
- [x] official (@arukuka) #26 
- [x] player (@arukuka) #27 
- [x] viewer (@takashi-chikayama) 1c123de

**Comment by takashi-chikayama** [comment]
Editor について、ゴールラインの先にも障害物を作れるように改訂しました。

いくらでも長いものを編集できるようにするのは結構面倒そうだったので、ゴール前の位置から視野に入る範囲までにしました。

編集する範囲が広がったこともあるので、表示のズームイン・アウトのボタンを追加しました。

ヘルプページも、これらの修正分と、時間制限やステップ数制限に対応しました。

それはよいのですが、git にはどうやって反映すればいいんでしたっけ。Master に 
commit しちゃっていいの？疑問だったので、とりあえず修正した editor 
以下の部分を
https://drive.google.com/file/d/1WU0kJZf5HUoXUjrKiJZ1lYL-ZKHPXe0b/view?usp=sharing
に入れました。

近山
# Javascript をメール添付させてくれないのは不便だなぁ…

**Comment by arukuka** [comment]
@takashi-chikayama 先生、修整ありがとうございます。

> Master にcommit しちゃっていいの？

大丈夫です。
お願いしてもよろしいでしょうか。

**Comment by takashi-chikayama** [comment]
作った branch の merge まではできたみたいなのですが、ユーザ名/パスワードがわからなくなってしまって push できていません。
Username は takashi-chikayama でいいのかな？
Password はどこにいってしまったろう…

近山

2017-11-10 21:51 GMT+09:00 Shingo Ohtsuka <notifications@github.com>:

**Comment by arukuka** [comment]
お手数をおかけします…。

> Username は takashi-chikayama でいいのかな？

おそらくそうだと思います。

> Password はどこにいってしまったろう…

httpsでgitリポジトリに接続しているようなので、
githubのパスワード（覚えてなければ再発行）で
できるかと思われます。

**Comment by takashi-chikayama** [comment]
むむ、そのgithubのパスワードがわからないのですが、再発行って自分でできるの？

近山

2017年11月11日 0:11 Shingo Ohtsuka <notifications@github.com>:

**Comment by arukuka** [comment]
`github password reset` で検索すると下記リンクがトップに来ますね…
（いきなりそのページがリンクされているのは少し驚きましたが）

https://github.com/password_reset

もしくは一度 [Sign out](https://github.com/logout) していただき、
[Sign in](https://github.com/login)から
[Forgot password?](https://github.com/password_reset) を
踏んでいただけると再発行できるようです
（リンク先は結局上記と同じですが）。

**Comment by takashi-chikayama** [comment]
どうもありがとう。たぶんうまくいったようです。

近山

2017年11月11日 0:23 Shingo Ohtsuka <notifications@github.com>:

**Comment by arukuka** [comment]
ありがとうございます。確認しました。

さしあたって以下のようなゴールライン以降に
障害物があるようなコースを作って試してみました。

[course.txt](https://github.com/SamurAI-Coding/Software2017-18/files/1461916/course.txt)
<img width="1064" alt="obstacled" src="https://user-images.githubusercontent.com/1694907/32666648-7a4e1844-c67b-11e7-92f6-bcd487b27bec.png">

viewerはまだ対応していませんが
greedy同士で対戦させてみたら
player0がゴールライン以降の障害物で
突っかかってくれているようです
（プレイヤー側も認識していて速度を修整ののちゴールします）。

<img width="1070" alt="obstacled" src="https://user-images.githubusercontent.com/1694907/32666839-2211eaf6-c67c-11e7-8353-42fb5d80da02.png">

[out.log](https://github.com/SamurAI-Coding/Software2017-18/files/1461900/out.log)
[stdin0.txt](https://github.com/SamurAI-Coding/Software2017-18/files/1461897/stdin0.txt)
[stdin1.txt](https://github.com/SamurAI-Coding/Software2017-18/files/1461899/stdin1.txt)

**Comment by takashi-chikayama** [comment]
動作確認、どうもありがとう。今日は昼は仕事があるのですが、夜には viewer も改版できると思います。

近山

2017年11月11日 1:04 Shingo Ohtsuka <notifications@github.com>:

**Comment by takashi-chikayama** [comment]
ゴールラインより先にある障害物に対応するように viewer を更新しました。簡単な動作確認だけはしていますが、不十分かも知れませんので、よろしく。
デバッグ用のレースログを作る過程で気付いたことがいくつか。これは別便で。

近山

2017年11月11日 9:23 Takashi Chikayama <takashi.chikayama@gmail.com>:

**Comment by arukuka** [comment]
遅くなってすみません、私も動作を確認しました。
このIssue はclose します。
