### ISSUE TITLE
Obstacles beyond the goal line

### ISSUE THREAD

**Issue by tanakat01** [SamurAI-Coding/Software2017-18#31]
現在のeditorでは，ゴール後の障害物として y座標が l + d の点まで指定できる．しかし，この障害物は，プレイヤのy座標がl - 1になっても観測できない．観測できない場所に障害物は無い方がよいのではないか? editorで作れるy座標は l+d - 1 までに制限した方が良いと思われる．
なお，現在は，viewerもy座標がl + d - 1 までの障害物にしか対応していない．そのため，y座標がl + d の障害物に阻まれてブロックされているプレイヤはブロックされていることはわかるものの，理由が分からない．

**Comment by takashi-chikayama** [comment]
ひとつ数え間違えてましたね。今夜中に修正します。

近山

2017/11/15 午後8:06 "tanakat01" <notifications@github.com>:

**Comment by arukuka** [comment]
ご指摘ありがとうございます
（確認がおろそかになってしまい、申し訳ないです）。

> 観測できない場所に障害物は無い方がよいのではないか? editorで作れるy座標は l+d - 1 までに制限した方が良いと思われる．

についてですが、実際にコースアウトになることは稀だとは思いますが
プレイヤーが賭けでスピードを上げたとき
<img src="https://latex.codecogs.com/gif.latex?\inline&space;y=l-1" /> にて視界外にも
障害物があることによってゴールができないコースがある、
というのもあっていいのではないかと思います
（作るかどうかはコース作者に委ねるとして）。
もっとも、*.smrjkyのjsonを直接修整しても良いですが。

上記の場合、viewerではどうスマートに表示できるかは思いつかないですね…。

**Comment by takashi-chikayama** [comment]
とりあえずは見えないところには障害がないようにしようと思います。修正は editor はもちろんですが、viewer
も見える範囲をひとつ狭めてもいいですよね。

既に遠くに作ってしまったコースがあると困るのですが、手作業で *.smrjky を修正するのはちょっと危険そうですよね。

   - .smrjky の内容をチェックするプログラムを作る
   （修正まで自動化するかは議論の余地あるかも）
   - official の方で無視する

のどちらかがよさそうに思います。

近山

2017年11月15日 21:18 Shingo Ohtsuka <notifications@github.com>:

**Comment by takashi-chikayama** [comment]
Editor を修正して commit+push しました。Viewer
も修正が必要と思っていたのは勘違いで、障害物のある範囲しか表示しないようにしてあったので、問題なさそうです。

近山

2017年11月15日 23:18 Takashi Chikayama <takashi.chikayama@gmail.com>:

**Comment by arukuka** [comment]
ありがとうございます。

見えないところには障害点を設けない件について、確認しました。
official の方で無視しようと思います
(warningとしてstderrに吐き出す形にします)。

**Comment by arukuka** [comment]
commit 確認しました。
今度は1つ少なかったため修整しました( 03e7df1 )。
length = 5, vision = 3 で以下のようになっています。

<img width="1053" alt="diff" src="https://user-images.githubusercontent.com/1694907/32882617-4e414b6e-caf8-11e7-8a6d-4aa22a7b069b.png">
（左から右にかけて新しく、下の文字列はcommit idです）

**Comment by arukuka** [comment]
すみません、今度はゴールラインが間違っていました…。
修整します。

**Comment by arukuka** [comment]
commit 確認しました。
今度は1つ少なかったため修整しました( 9e94e00 )。
length = 5, vision = 3 で以下のようになっています。

<img width="1053" alt="diff" src="https://user-images.githubusercontent.com/1694907/32884018-57247720-cafc-11e7-9591-f440ebc5d5a6.png">

（左から右にかけて新しく、下の文字列はcommit idです）

**Comment by arukuka** [comment]
official で余分な分をwarning出して無視するようにしました : bb349f7

このissue を closeします。
